### ISSUE TITLE
JOTTing down some thoughts

### ISSUE THREAD

**Issue by joehutcheson** [CallumAlexander/JOTT#1]
I see you are using bash variables in this. Is there a potential hazard involved in this if it overwrites variables used by other programs? 

Also, have you considered rewriting it in Haskell?

**Comment by CallumAlexander** [comment]
Agreed, I also believe that the jott.cfg variables need to be validated. 

Furthermore, maybe not storing the glossary URL in a variable. No harm in hard-coding it into the curl request.
